### ISSUE TITLE
how do  you use this bundle via "Payum/PayumBundle"?

### ISSUE THREAD

**Issue by videni** [labs7in0/omnipay-wechat#1]
Hi, do you know how to use this bundle via "Payum/PayumBundle"?

**Comment by kinosang** [comment]
This package is designed to work with `Omnipay/Omnipay`. If you need WeChat gateway for `Payum/PayumBundle`, you need to rewrite it or just use `overtrue/wechat` which is a standalone package for WeChat MP (including WeChat payment).
