### ISSUE TITLE
不能支付。。

### ISSUE THREAD

**Issue by unizhu** [labs7in0/omnipay-wechat#3]
使用  $omnipay->purchase($params)->send(); 后
`
UnexpectedValueException in Response.php line 395:
The Response content must be a string or object implementing __toString(), "object" given.
in Response.php line 395
at Response->setContent(object(WechatPurchaseResponse)) in Response.php line 54
at Response->setContent(object(WechatPurchaseResponse)) in Response.php line 198
at Response->__construct(object(WechatPurchaseResponse)) in Router.php line 1225
at Router->prepareResponse(object(Request), object(WechatPurchaseResponse)) in ControllerDispatcher.php line 113
`

另外请问能不能增加一个传参数给ios或者android的方法。现在都是写死For Web的。

谢谢。

**Comment by kinosang** [comment]
这个问题看起来像是环境问题，可否提供更多调试信息？

传参数给iOS或Android是指调用 WeChat 客户端支付？目前因为个人能力有限暂时没有实现（最早期版本就是用了 JSAPI，结果一直提示权限问题无法正常工作

**Comment by unizhu** [comment]
环境：
Larval 5.1.x
php 5.6.11

给iOS，Android的，应该是取得prepay id 后，不发起支付，而是可以有方法拿到这些参数后，返回给手机客户端。我看了下代码，这些参数都应该在 $omnipay->purchase($params) 里，只要提供方法返回出来，不需要send应该可以了。

**Comment by kinosang** [comment]
取得prepay id可以用 prePurchase->send，這個會返回一個包含prepay id的數組或拋出一個錯誤。

**Comment by unizhu** [comment]
那网页版的麻烦看下为什么会出错，谢谢拉。

Regards,

Uni

**Comment by kinosang** [comment]
刚刚参加完一场hack马拉松，正在回程途中，将在明日到达后尽快处理

**Comment by unidotnet** [comment]
使用 prePurchase->send 出错。。


exception 'ErrorException' with message 'Undefined property:
Omnipay\WeChat\ExpressGateway::$prePurchase'


Regards,

Uni

**Comment by unizhu** [comment]
haha..hack马拉松在哪里举办啊？

**Comment by kinosang** [comment]
上海

**Comment by kinosang** [comment]
已经为purchase添加了相关接口，将在到站后push

**Comment by unizhu** [comment]
上海国际马拉松啊。。昨天雾霾200.。。外滩一圈全部封路了，我下午才能开进去。

Regards,

Uni

**Comment by unizhu** [comment]
好的，谢谢。放到 packagist.org ,我直接composer update。

Regards,

Uni

**Comment by kinosang** [comment]
这个patch不会发行新的release，届时你需要调整composer.json使用 dev-master branch。
另，你好像误解 hackathon 为马拉松了，这是指马拉松式的开发赛事。

**Comment by unidotnet** [comment]
hackathon 是谁家举办的？SegmentFault 还是啥？


Regards,

Uni

**Comment by unizhu** [comment]
对了，prePurchase->send , 能不能把timestamp一起返回出来？

**Comment by unizhu** [comment]
还有2个问题是：
1. prePurchase->send签名错误, 然而返回的是code_url 的exception.
2. getParamsToSign ： 'seller_id'=> $this->getPartner(), 这里应该是getSellerEmail()吧，不然和partner是同一个了。

**Comment by kinosang** [comment]
工作環境用電腦送修了， 歡迎 pull request。提示簽名錯誤極有可能是你配置參數有問題，比如 key 應該是 公眾平台開發者key，不是支付平台key

-- Sent with iOS Mail.app
Chino Chang
Website: 7in0.me
E-mail: me@7in0.me

**Comment by unizhu** [comment]
我换了个公众号，才搞错了key，可是我用的是支付的key哎，成功签名了。

Regards,

Uni

**Comment by unizhu** [comment]
好像还是不能pull request啊。。代码没更新过

**Comment by kinosang** [comment]
@unidotnet pull request 是指你修改了代码之后提交到主仓库。另外，之前说的问题不是解决了么？

**Comment by unizhu** [comment]
不是的，你理解错了。
我只是解决了签名问题，这个和你的代码没有关系。
我是看到你说为purchase增加了send的方法，准备push，但是没看到你push。
我想pull的是你最新的代码。

谢谢啦。
